In [1]:
import numpy as np

In [109]:
num = input("幾個矩陣")
if num == "":
    num = 2
else:
    num = int(num)
    
out = []
for i in range(num):
    A = input(">>")
    A = A.split(" ")
    shapes = np.sqrt(len(A)).astype(int)
    A = np.array(A).reshape(shapes,np.sqrt(len(A)).astype(int)).astype(int)
    out.append(A)
temp = np.identity(shapes)
for j in range(num-1):
    temp = np.dot(temp, out[j])
print(temp)

幾個矩陣
>>


ValueError: invalid literal for int() with base 10: ''

In [111]:
out[1]

IndexError: list index out of range

In [139]:
E = np.array([
    [1,0,0],
    [2,1,0],
    [1,2,1]
])
A = np.array([[-2,  1,  2],
       [ 4,  1, -2],
       [-6, -3,  4]])
np.dot(E,A)

array([[-2,  1,  2],
       [ 0,  3,  2],
       [ 0,  0,  2]])

In [135]:
E1 = np.array([
    [1,0,0],
    [-2,1,0],
    [3,-2,1]
])

In [136]:
np.dot(E1,E)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [130]:
E

array([[ 1,  0,  0],
       [ 2,  1,  0],
       [-3,  0,  1]])

In [117]:
E = np.array([
    [1,0,0],
    [2,1,0],
    [-3,0,1]
])
A = np.array([[-2,  1,  2],
       [ 4,  1, -2],
       [-6, -3,  4]])
np.dot(E,A)

array([[-2,  1,  2],
       [ 0,  3,  2],
       [ 0, -6, -2]])

In [105]:
temp = np.identity(shapes)
for j in range(num):
    temp = np.dot(temp, out[j])

In [107]:
temp

array([[ -2.,   1.,   2.],
       [  0.,   3.,   2.],
       [ 24.,   0., -14.]])

In [106]:
 out[0]


array([[ 1,  0,  0],
       [ 2,  1,  0],
       [-3,  6,  1]])

In [84]:
import scipy
from scipy.linalg import lu

In [98]:
for i in lu(out[1]):
    print(i.astype(np.float16))

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[ 1.   0.   0. ]
 [-0.4  1.   0. ]
 [ 0.2 -0.   1. ]]
[[ 5.   5.   6. ]
 [ 0.   4.   9.4]
 [ 0.   0.  -0.2]]


In [96]:
-4.00000000e-01

-0.4

In [99]:
for i in lu(np.array([
    [-2,1,2],
    [4,1,-2],
    [-6,-3,4]
])):
    print(i)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.          0.          0.        ]
 [ 0.33333333  1.          0.        ]
 [-0.66666667 -0.5         1.        ]]
[[-6.         -3.          4.        ]
 [ 0.          2.          0.66666667]
 [ 0.          0.          1.        ]]


In [138]:
L = np.array([
    [1,0,0],
    [-2,1,0],
    [3,-2,1]
])
U = np.array([
    [-2,  1,  2],
    [0,3,2],
    [0,0,2]
])
np.dot(L,U)

array([[-2,  1,  2],
       [ 4,  1, -2],
       [-6, -3,  4]])

In [88]:
out[1]

array([[ 1,  1,  1],
       [ 5,  5,  6],
       [-2,  2,  7]])

In [78]:
temp

array([[1., 1., 1.],
       [0., 0., 1.],
       [0., 4., 9.]])

In [67]:
A

array([[ 1,  1,  1],
       [ 5,  5,  6],
       [-2,  2,  7]])

In [63]:
" ".join(list(A.reshape(-1).astype(str)))

'1 0 0 -5 1 0 2 0 1'

In [44]:
A = np.array([
    [1,0,0],
    [1,1,0],
    [1,1,1]
])

In [45]:
len(A)

3

In [43]:
np.dot(A, A)

array([[1, 0, 0],
       [2, 1, 0],
       [3, 2, 1]])

In [28]:
A.dot(A)

array([[19, 30],
       [12, 19]])

In [31]:
A

array([[3, 5],
       [2, 3]])

In [4]:
A = np.array([
    [2,1,0],
    [4,3,2],
    [-2,-1,2]
])
B = np.array([
    [4/2, -1/2, 1/2],
    [-3,1,-1],
    [1/2, 0, 1/2]
])
np.dot(A,B)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
A = np.array([
    [1,1,1],
    [3,5,6],
    [-2,2,7]
])

In [22]:
E1 = np.array([
    [1,0,0],
    [-3,1,0],
    [2,0,1]
])
E2 = np.array([
    [1,0,0],
    [0,1,0],
    [0,-2,1]
])


In [34]:
np.dot(E2,np.dot(E1,A))

array([[1, 1, 1],
       [0, 2, 3],
       [0, 0, 3]])

In [35]:
U = np.array([
    [1,1,1],
    [0,2,3],
    [0,0,3]
])


In [36]:
np.dot(np.linalg.inv(E1), np.linalg.inv(E2))

array([[ 1.,  0.,  0.],
       [ 3.,  1.,  0.],
       [-2.,  2.,  1.]])

In [37]:
np.dot(np.dot(np.linalg.inv(E1), np.linalg.inv(E2)),U)

array([[ 1.,  1.,  1.],
       [ 3.,  5.,  6.],
       [-2.,  2.,  7.]])

In [19]:
E1.dot(A)

array([[ 1,  1,  1],
       [ 0,  2,  3],
       [ 3,  9, 15]])

In [39]:
A = np.array([
    [1,-3,-4],
    [-1,1,-3],
    [0,1,-3]
])
B = np.array([1,14,5])

In [40]:
np.linalg.solve(A,B)

array([-9.        , -0.76923077, -1.92307692])

In [50]:
10/13

0.7692307692307693

In [43]:
-25/13

-1.9230769230769231

In [44]:
141/13

10.846153846153847

In [46]:
13*9

117

In [48]:
16*6 + 45

141

In [45]:
np.linalg.inv(A)

13.0