In [13]:
import numpy as np

In [1]:
"5, 10, 3, 12, 5, 50, 6".split(", ")

['5', '10', '3', '12', '5', '50', '6']

In [9]:
matrix = input(">> ")
if matrix == "":
    matrix = "5, 10, 3, 12, 5, 50, 6"
    matrix = "30, 35, 15, 5, 10, 20, 25"
matrix = matrix.split(", ")
matrix = np.array(matrix).astype(int)
x = len(matrix)
m = np.zeros((x,x))
s = np.zeros((x,x))

>> 


In [10]:
for i in range(2,x):
    for j in range(1,x-i+1):
        k = i+j-1
        m[j, k] = float("inf")
        for q in range(j, k):
            temp = matrix[j-1]*matrix[q]*matrix[k] + m[j,q] + m[q+1,k]
            #print("%d*%d*%d+%d+%d=%d"%(matrix[j-1],matrix[q],matrix[k] , m[j,q] , m[q+1,k],temp))
            if temp<m[j,k]:
                m[j,k] = temp
                s[j,k] = q
        #print(j,k)
        
        #print(out)

In [11]:
s

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 3., 3., 3.],
       [0., 0., 0., 2., 3., 3., 3.],
       [0., 0., 0., 0., 3., 3., 3.],
       [0., 0., 0., 0., 0., 4., 5.],
       [0., 0., 0., 0., 0., 0., 5.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [12]:
m

array([[    0.,     0.,     0.,     0.,     0.,     0.,     0.],
       [    0.,     0., 15750.,  7875.,  9375., 11875., 15125.],
       [    0.,     0.,     0.,  2625.,  4375.,  7125., 10500.],
       [    0.,     0.,     0.,     0.,   750.,  2500.,  5375.],
       [    0.,     0.,     0.,     0.,     0.,  1000.,  3500.],
       [    0.,     0.,     0.,     0.,     0.,     0.,  5000.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0.]])

In [92]:
s

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 2., 2., 4., 2.],
       [0., 0., 0., 2., 2., 2., 2.],
       [0., 0., 0., 0., 3., 4., 4.],
       [0., 0., 0., 0., 0., 4., 4.],
       [0., 0., 0., 0., 0., 0., 5.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [66]:
if times < m[j,k]:
            m[j,k] = times
            s[j,k] = j
        for k in range(j-2,j+1):
            break
            print(k," ->", end= "")
            out *= matrix[k]
            print(matrix[k])
        print(i, j)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 0., 0., 5.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [211]:
def LCS(X, Y):
    #X = "A, B, C, B, D, A, B".split(", ")
    #Y = "B, D, C, A, B, A".split(", ")
    lenX = len(X)
    lenY = len(Y)

    import numpy as np
    c = np.zeros((lenX+1, lenY+1))
    b = np.zeros((lenX+1, lenY+1)).astype(int).astype(str)
    
    for x in range(lenX):
        for y in range(lenY):
            if X[x] == Y[y]:
                c[x+1,y+1] = c[x, y] + 1
                b[x+1,y+1] = "↖"
            elif c[x+1, y] > c[x, y+1]:
                c[x+1,y+1] = c[x+1, y]
                b[x+1,y+1] = "←"
            else:
                c[x+1,y+1] = c[x, y+1]
                b[x+1,y+1] = "↑"
                
    def printLCS(b, X, x, y, out):
        if x==0 or y==0:
            return
        if b[x,y] == "↖":
            out.append(X[x-1])
            printLCS(b,X, x-1, y-1, out)
        elif b[x,y] == "↑":
            printLCS(b, X, x-1, y, out)
        else:
            printLCS(b, X, x, y-1, out)
    LCS = []
    printLCS(b, X, lenX, lenY, LCS)
    print(LCS)
    out = []
    for C, B in zip(c, b):
        for cs, bs in zip(C, B):
            if bs == "0":
                #print("%d\t"%(cs), end = "")
                out.append("%d"%cs)
            else:
                #print("%s %d\t"%(bs, cs), end = "")
                out.append("%s %d"%(bs,cs))
    out = np.array(out)
    out = out.reshape(lenX+1, lenY+1)
    import pandas as pd
    return pd.DataFrame(out, index = ["Xi"] + X, columns = ["Yi"] + Y), LCS

In [212]:
out = LCS("1, 0, 0, 1, 0, 1, 0, 1".split(", "), "0, 1, 0, 1, 1, 0, 1, 1, 0".split(", "))

['0', '1', '1', '0', '0', '1']


In [214]:
out[0]

Yi    0    1    0    1    1    0    1    1    0
Xi  0    0    0    0    0    0    0    0    0    0
1   0  ↑ 0  ↖ 1  ← 1  ↖ 1  ↖ 1  ← 1  ↖ 1  ↖ 1  ← 1
0   0  ↖ 1  ↑ 1  ↖ 2  ← 2  ← 2  ↖ 2  ← 2  ← 2  ↖ 2
0   0  ↖ 1  ↑ 1  ↖ 2  ↑ 2  ↑ 2  ↖ 3  ← 3  ← 3  ↖ 3
1   0  ↑ 1  ↖ 2  ↑ 2  ↖ 3  ↖ 3  ↑ 3  ↖ 4  ↖ 4  ← 4
0   0  ↖ 1  ↑ 2  ↖ 3  ↑ 3  ↑ 3  ↖ 4  ↑ 4  ↑ 4  ↖ 5
1   0  ↑ 1  ↖ 2  ↑ 3  ↖ 4  ↖ 4  ↑ 4  ↖ 5  ↖ 5  ↑ 5
0   0  ↖ 1  ↑ 2  ↖ 3  ↑ 4  ↑ 4  ↖ 5  ↑ 5  ↑ 5  ↖ 6
1   0  ↑ 1  ↖ 2  ↑ 3  ↖ 4  ↖ 5  ↑ 5  ↖ 6  ↖ 6  ↑ 6

In [179]:
def Hi():
    print("HI")
    return

<function __main__.Hi()>