In [106]:
import numpy as np 

x = np.array([
        [1,-2,1],
    [-1,1,1],
    [0,1,1]
]) 
y = np.linalg.inv(x)

In [115]:
y = np.array([
    [0,-1,1],
    [-1/3, -1/3, 2/3],
    [1/3, 1/3, 1/3]
])
np.linalg.det(y)

-0.3333333333333333

In [116]:
np.linalg.det(x)

-3.0000000000000004

In [111]:
np.dot(y,x)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [112]:
A = np.array([
    [2,2,0],
    [1,1,2],
    [1,1,2]
])

In [114]:
np.dot(y,np.dot(A, x))

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 4.]])

In [7]:
j = 0
for i in range(1000):
    j += (3/2)**i*i
j < 2**1000

True

In [8]:
import numpy as np

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
#第二題
def question2(array, i=0, j=-1):
    if j == -1:
        lens = len(array)
        j = len(array) - 1
    if abs(i - j) == 1:
        #只剩一個，base case。
        return i
    index = int(i+ abs(i-j)/2)
    print(i, j)
    if array[index - 1] > array[index]:
        #此位置遞減，找前面
        return question2(array, i, index)
    elif array[index - 1] < array[index]:
        #此位置遞增，找後面
        return question2(array, index, j)
    else:
        #不高不低，兩邊都要找
        right, left = question2(array, i, index), question2(array, index, j)
        return max(array[right], array[left])


#測資
test = list(np.arange(9)) +  list(np.arange(3)[::-1])
print(test)

print(question2(test))


In [101]:
%%time
import pandas as pd
import numpy as np


#隨機生成任務
Tasks = pd.DataFrame(columns= ["TaskID", "Start", "End"])

maxLen = 17
Tasks["TaskID"] = np.array(list(map(lambda x: "Task "+str(x), np.arange(0,11))))
Tasks["Start"] = np.random.randint(1, maxLen - 1, len(Tasks.TaskID))
Tasks["End"] = Tasks["Start"].apply(lambda x:x + np.random.randint(1, maxLen-x))

#隨機生成價值
Tasks["Value"] = Tasks.End.apply(lambda x: np.random.randint(1,10))

Tasks = Tasks.sort_values("End")
#將任務從最晚開始的開始排列

#print(Tasks)


Tasks

#使用 devide and conquer 
#code ，沒時間完成，沒有測試
#沒時間debug，但概念是有的，希望老師從寬給分
ChoosenTasks = []
def getValue(subTasks):
    global ChoosenTasks
    maxValue = 0
    outTar = []
    lens = len(subTasks)
    print(lens)
    if lens==0:
        #Base case: 沒有任務
        return 0, []
    elif lens ==1: #只有一個任務，就回傳吧！
        tar = subTasks[0:1]
        return tar.Value, [tar]
    for i in range(lens):
        tar = subTasks[i:i+1] #把子任務的每一個都抽出來檢查
        #檢查有此任務在的情況下，價值的總和
        values = tar.Value
        targetAft = Tasks[(Tasks.Start) > list(tar.End)[0]][0:1] 
        aft, tarAft = getValue(targetAft)
        #建立子集合，範圍在目標任務結束之後
        targetBef = Tasks[(Tasks.End) < list(tar.Start)[0]][0:1] 
        bef, tarBef = getValue(targetBef)
        #建立子集合，範圍在目標任務開始之前
        #然後檢查
        #看看有這個任務的情況下，是不是有最多價值。
        #如果是，那就把他放進要回傳的選項
        if maxValue < tar.Value+bef+aft:
            maxValue = tar.Value+bef+aft
            outTar = [tar]+tarBef+tarAft
    return maxValue, outTar #回傳最大價值，以及最大價值下的任務們
getValue(Tasks)

11
1
0


ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

RecursionError: maximum recursion depth exceeded while calling a Python object

In [ ]:
startTime = 0
toDo = []
i = 0
while startTime <= max(Tasks.Start):
    target = Tasks[Tasks.Start >= startTime][0:1]
    toDo.append(list(target.TaskID)[0])
    startTime = list(target.End)[0]+1

In [102]:



LastStartTime = max(Tasks.Start) + 1
toDo = []
i = 0
while LastStartTime >= min(Tasks.End): #如果子集合還有任務可以選
    target = Tasks[Tasks.End <= LastStartTime][0:1] #建立子集合
                                    #並選擇第一個（也就是子集合中最晚開始的）
    toDo.append(list(target.TaskID)[0])#將此任務放進最佳解中
    LastStartTime = list(target.Start)[0]-1 #將子集合範圍設定為此任務開始前的任務們
print(toDo)

['Task 5']


In [ ]:
import numpy as np
def OptimalBST(p,q,n):
    e = np.zeros((n+1, n))
    w = np.zeros((n+1, n))
    for i in range(1,n+1+1):
        e[i, i-1] = q[i-1]
        w[i, i-1] = q[i-1]
    for l in range(1, n+1):
        for i in range(l,n-l+1+1):
            j = i+l-1
            e[i,j] = float("inf")
            w[i,j] = w[i, j-1] + p[j] + q[j]
            for r in range(i,j+1):
                t = e[i, r-1]+e[r+1, j]+ w[i,j]
                if t < e[i,j]:
                    e[i,j] = t
                    root[i,j] = r
    return e, root