In [1]:
import numpy as np

In [12]:
E = np.array([
    [1,1,2],
    [1,2,3],
    [1,2,4]
])
A = np.array([[2,0,-1],
       [-1,2,-1],
       [0,-1,1]])
np.dot(E,A)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
np.linalg.inv(E)

array([[ 2.,  0., -1.],
       [-1.,  2., -1.],
       [ 0., -1.,  1.]])

In [13]:
A = np.array([[2,0,-1],
       [-1,2,-1],
       [0,-1,1]])

In [14]:
V = np.array([
    [4,0,0],
    [6,1,1],
    [7,1,2]
])

In [15]:
np.dot(A,V)

array([[ 1, -1, -2],
       [ 1,  1,  0],
       [ 1,  0,  1]])

In [17]:
import scipy

In [20]:
from scipy import linalg

In [23]:
linalg.lu(A)[0]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
A = np.array([
    [ 1,1,1],
    [ 3,5,6],
    [ -2,2,7]
])

In [33]:
linalg.lu(A)[1]

array([[ 1.        ,  0.        ,  0.        ],
       [-0.66666667,  1.        ,  0.        ],
       [ 0.33333333, -0.125     ,  1.        ]])

In [34]:
np.dot(linalg.lu(A)[1],linalg.lu(A)[2])

array([[ 3.,  5.,  6.],
       [-2.,  2.,  7.],
       [ 1.,  1.,  1.]])

In [50]:
A = np.array([
    [0,1,0],
    [1,0,0],
    [0,0,1]
])

In [51]:
A.dot(A)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [41]:
(-141/13) + -3*(80/13) + (-4*(-25/13))

-21.615384615384617